version: "3"
services: 
  desafio-db:
    image: postgres:11
    container_name: desafio-db
    restart: always
    environment:
      - POSTGRES_DB=desafio-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432